languages:
  python:
    run: "python3 {source}"
  cpp:
    compile: "g++ -O3 -std=c++11 {source} -o {out}"
    run: "{out}"
  rust:
    compile: "rustc -O {source} -o {out}"
    run: "{out}"
  javascript:
    run: "node {source}"

  java:
    compile: "javac Main.java"
    run: "java Main"

  csharp:
    # Assumes a .csproj exists in the directory
    compile: "dotnet build -c Release"
    run: "dotnet run -c Release --no-build"
  go:
    compile: "go build -o {out} {source}"
    run: "{out}"
dependencies:
  rust: [rand]
